// app/layout.tsx
import { AppProviders } from '@module/providers';
import { pretendard, suite } from '@module/lib/font';
import '@module/styles/globals.css';
import type { Metadata, Viewport } from 'next';
import AppLayoutShell from '@component/layout/app-layout-shell';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} ${suite.variable} font-pretendard bg-white text-gray-900`}
      >
        <AppProviders>
          <AppLayoutShell>{children}</AppLayoutShell>
        </AppProviders>
      </body>
    </html>
  );
}
